server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
         uri: https://github.com/Nagarajujunna90/config_repo.git
         username: Nagarajujunna90
         password: Nagaraju@23v
         default-label: master
         clone-on-start: true
